services:
  database:
    container_name: database
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: ${POSTGRES_PGDATA}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - db-network
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PGDATA: ${POSTGRES_PGDATA}
    depends_on:
      - database
    networks:
      - db-network
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8081:80"
    networks:
      - db-network
    restart: always

volumes:
  postgres_data:

networks:
  db-network: